# Generated by Django 6.1.1 on 2026-09-12 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MothSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(help_text='Name of the moth species', max_length=200)),
                ('sighting_date', models.DateField(help_text='Date you saw it')),
                ('location', models.CharField(help_text='Where you saw it', max_length=300)),
                ('notes', models.TextField(blank=True, help_text='Any extra notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
