# Generated by Django 6.1.1 on 2026-09-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mothsighting',
            name='species_name',
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='authority',
            field=models.CharField(blank=True, max_length=200, verbose_name='Authority'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='county',
            field=models.CharField(blank=True, default='Suffolk', max_length=100, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='grid_reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grid Ref'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='method',
            field=models.CharField(blank=True, max_length=200, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='parent',
            field=models.CharField(blank=True, max_length=300, verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Number Seen'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='refers_to',
            field=models.CharField(blank=True, max_length=300, verbose_name='Refers To'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='sighting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='source',
            field=models.TextField(blank=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='status',
            field=models.CharField(blank=True, default='None', max_length=100, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='taxon',
            field=models.CharField(default='', max_length=300, verbose_name='Taxon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='taxon_type',
            field=models.CharField(blank=True, default='Species', max_length=100, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='vernacular',
            field=models.CharField(blank=True, max_length=300, verbose_name='Vernacular'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='weather',
            field=models.CharField(blank=True, max_length=300, verbose_name='Weather'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='location',
            field=models.CharField(max_length=300, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='sighting_date',
            field=models.DateField(verbose_name='Date Sighted'),
        ),
    ]
