# Generated by Django 6.1.1 on 2026-09-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_mothsighting_species_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mothsighting',
            options={'ordering': ['-sighting_date']},
        ),
        migrations.RemoveField(
            model_name='mothsighting',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='mothsighting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mothsighting',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='mothsighting',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='mothsighting',
            name='sighting_time',
        ),
        migrations.RemoveField(
            model_name='mothsighting',
            name='source',
        ),
        migrations.RemoveField(
            model_name='mothsighting',
            name='taxon_type',
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='determiner',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Determiner'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='recorder',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Recorder'),
        ),
        migrations.AddField(
            model_name='mothsighting',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='county',
            field=models.CharField(blank=True, default='Suffolk', max_length=100, verbose_name='Vice County'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='grid_reference',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Grid Ref'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Site / Location'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='method',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='refers_to',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Refers To'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='taxon',
            field=models.CharField(max_length=300, verbose_name='Taxon (Scientific Name)'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='vernacular',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Vernacular (Common Name)'),
        ),
        migrations.AlterField(
            model_name='mothsighting',
            name='weather',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Weather / Conditions'),
        ),
    ]
